### ISSUE TITLE
Support ValueRecorder export

### ISSUE THREAD

**Issue by nicolasgere** [GoogleCloudPlatform/opentelemetry-operations-js#176] opened 2020-09-30 00:08 UTC
Please answer these questions before submitting a bug report.

### What version of OpenTelemetry are you using?
0.10.2

### What version of Node are you using?
10.4

### What did you do?
Just want to use ValueRecorder

### Additional context
Based on https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/blob/07da5214d92618e0e49c6f691afd72d796a09e29/packages/opentelemetry-cloud-monitoring-exporter/src/transform.ts#L92 it will be done. Do you know when? do you know a work around?

**Comment by aabmass** [comment] 2020-09-30 02:40
The aggregation behavior for ValueRecorder is under a lot of debate in the spec https://github.com/open-telemetry/opentelemetry-specification/issues/636. It looks it will probably change to some sort of Histogram or sketch. That said, we could probably send LastValue that is currently give in OTel JS.

**Comment by aabmass** [comment] 2021-02-01 16:33
Duplicate of #129, closing in favor of that issue

**Closed by aabmass** 2021-02-01 16:33 UTC
Labels: bug, enhancement, good first issue, monitoring
