### ISSUE TITLE
Initialize without specifying a project ID

### ISSUE THREAD

**Issue by inlined** [GoogleCloudPlatform/opentelemetry-operations-js#98] opened 2020-06-19 17:40 UTC
### Problem
Google Cloud Functions and Google Cloud Run are constrained to not include the `CLOUD_PROJECT_ID` environment variable anymore in order to comply with the Knative runtime contract. This means that GCE, GCF, and Run customers must all manually inject a project ID into the application to initialize the stackdriver collector.

### Recommendation
It should be possible to auto-initialize the SDK in GCP environments without specifying a project Id. The ID can be cheaply fetched from the [local metadata server](https://cloud.google.com/compute/docs/storing-retrieving-metadata) at `http://metadata.google.internal/computeMetadata/v1/project/project-id`. This would increase the simplicity of using OpenTelemetry for Stackdriver and encourage portable code.

### Alternatives considered
Per my [sample tracing app](https://github.com/inlined/fib/blob/master/package.json#L12), I manually inject the project as an environment variable dynamically determined with `gcloud config get-var core/project`. This is unintuitive for many and seems overkill.

**Comment by jonahrosenblum** [comment] 2020-06-22 18:24
Hi, I can give this a shot. Could I claim this issue?

**Comment by steren** [comment] 2020-06-22 20:32
Note that all GCP Compute products expose the project ID in a unified way at `http://metadata.google.internal/computeMetadata/v1/project/project-id`

So looking for project ID there would not only deliver a great developer experience on Cloud Functions and Cloud Run, ut also on Kubernetes Engine and Compute Engine.

**Comment by jonahrosenblum** [comment] 2020-06-24 16:10
Hello, I have not been able to reproduce the problem. I looked into the GoogleAuth library and it seems like it does query the metadata for the project id already which I think makes my code redundant. I can point to which sections of code I believe do this if needed, but I may be misunderstanding some things.

**Comment by steren** [comment] 2020-06-24 16:51
If OpenTelemetry already fetches project ID from the GCP instance metadata server and doesn ot require to provide it explicitly as a config, then we can close this issue.

Do you confirm the behavior?

**Comment by jonahrosenblum** [comment] 2020-06-24 21:29
To test this I created a very simple GCP cloud function which creates a google auth object with no project id specified, and an endpoint which would call the getProjectId() function used in our codebase (to see if we can pull the project id with no environment variable). I found that it was correctly able to determine the project id, I can provide the code sample I used if that would help at all. I would request that this issue is not closed until I have communicated with @inlined about the problem a little bit more.

I believe this works because looking at the google auth library source code we can see that the getProjectId function calls several functions to try and determine the project id, one of which is called getGCEProjectId which in turn queries the GCP metadata for an id. I think adding a unit test to demonstrate this would be nice, but I am not sure how to accurately mock the GCE environment. Let me know if I am mistaken about something or have any feedback!

**Comment by steren** [comment] 2020-06-24 21:31
Great.
We should also confirm on a vanilla GCE instance and a Cloud Run service.

**Comment by jonahrosenblum** [comment] 2020-06-26 17:25
I added a simple unit test to demonstrate how this works, hopefully this addresses this issue.

**Comment by inlined** [comment] 2020-06-30 00:42
Per Steren's liniked bug, I made assumptions based on the documentation. When the documentation told me to assert without the environment variable it didn't occur to me to try anyway.

**Comment by jonahrosenblum** [comment] 2020-06-30 00:53
Just to clarify, when you took out the project id it still worked, yes?

**Comment by punya** [comment] 2021-02-01 16:06
Closing out as stale -- please reopen if there are additional questions.

**Closed by punya** 2021-02-01 16:06 UTC

**Comment by steren** [comment] 2021-02-01 17:00
This bug needs to be re-opened as the issue still exists, it's not because the OpenTelemetry tam hasn't addressed it in a few months that it should be closed.

I cannot re-open.

**Comment by aabmass** [comment] 2021-02-01 19:40
@steren I believe this issue is solved, unless I'm missing something from the comments above.

> If OpenTelemetry already fetches project ID from the GCP instance metadata server and doesn ot require to provide it explicitly as a config, then we can close this issue.

This is the case, google-auth-library queries the project ID if it's missing.

**Comment by steren** [comment] 2021-02-01 19:42
Ah great, sorry I forgot it was already doing it. Yes, then let's close this issue as fixed,

**Comment by aabmass** [comment] 2021-02-01 20:09
Just tested in Cloud Run and it picks up the project ID alright. Sorry for the confusion
